sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t ffreitasit/docker-complex-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ffreitasit/docker-complex-react npm run test

after_success:
  - docker build -t ffreitasit/multi-client ./client
  - docker build -t ffreitasit/multi-nginx ./nginx
  - docker build -t ffreitasit/multi-server ./server
  - docker build -t ffreitasit/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ffreitasit/multi-client
  - docker push ffreitasit/multi-nginx
  - docker push ffreitasit/multi-server
  - docker push ffreitasit/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-860437045614'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: '$AWS_SECRET_KEY'
